runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /_ah/.*
  script: _go_app

- url: /admin/.*
  script: _go_app
  login: admin

- url: /api/.*
  script: _go_app
  login: required

- url: /leaders/.*
  script: _go_app

- url: /static
  static_dir: static
